fix deploy

diff --git a/.github/workflows/deploy.yaml b/.github/workflows/deploy.yaml
--- a/.github/workflows/deploy.yaml
+++ b/.github/workflows/deploy.yaml
@@ -1,4 +1,5 @@
-name: Deploy
+name: CD
+
 on:
   release:
     types: [published]
@@ -6,6 +7,7 @@ on:
 jobs:
   deploy:
     runs-on: ubuntu-latest
+
     permissions:
       contents: read
       packages: read
@@ -18,8 +20,8 @@ jobs:
       - name: Prepare Image Name
         id: prep
         run: |
-          echo "repo_lower=$(echo ${{ github.repository }} | tr '[:upper:]' '[:lower:]')" >> $GITHUB_OUTPUT
-          echo "release_sha=$(git rev-list -n 1 ${{ github.event.release.tag_name }})" >> $GITHUB_OUTPUT
+          echo "repo_lower=$(echo '${{ github.repository }}' | tr '[:upper:]' '[:lower:]')" >> $GITHUB_OUTPUT
+          echo "release_sha=${{ github.event.release.target_commitish }}" >> $GITHUB_OUTPUT
 
       - name: Remote Docker Deploy
         uses: appleboy/ssh-action@v1.0.3
@@ -28,12 +30,23 @@ jobs:
           username: semen
           key: ${{ secrets.SSH_PRIVATE_KEY }}
           port: 3122
+          command_timeout: 20m
           script: |
             IMAGE="ghcr.io/${{ steps.prep.outputs.repo_lower }}:${{ steps.prep.outputs.release_sha }}"
             CONTAINER_NAME="catty-container"
 
             echo "Pulling image: $IMAGE"
-            docker pull "$IMAGE"
+
+            i=1
+            until docker pull "$IMAGE"; do
+              if [ "$i" -ge 5 ]; then
+                echo "Docker pull failed after $i attempts"
+                exit 1
+              fi
+              echo "Docker pull failed, retry $i/5 in 15 seconds..."
+              i=$((i+1))
+              sleep 15
+            done
 
             docker stop "$CONTAINER_NAME" || true
             docker rm "$CONTAINER_NAME" || true
