update deploy 9

diff --git a/.github/workflows/deploy.yaml b/.github/workflows/deploy.yaml
--- a/.github/workflows/deploy.yaml
+++ b/.github/workflows/deploy.yaml
@@ -12,7 +12,7 @@ on:
 jobs:
   deploy:
     runs-on: ubuntu-latest
-    if: ${{ github.event_name == 'release' || (github.event.workflow_run.conclusion == 'success' && github.event.workflow_run.head_branch == 'lab4') }}
+    if: ${{ github.event_name == 'release' || (github.event_name == 'workflow_run' && github.event.workflow_run.conclusion == 'success' && github.event.workflow_run.head_branch == 'lab4') }}
     steps:
       - name: Deploy via SSH
         uses: appleboy/ssh-action@v1.0.3
@@ -35,12 +35,13 @@ jobs:
             
             TARGET_SHA="${{ github.event.workflow_run.head_sha || github.sha }}"
             
-            echo "DEPLOY_REF=$TARGET_SHA" > .env
-            echo "IMAGE=ghcr.io/kuzminstanislav/catty-reminders-app:$TARGET_SHA" >> .env
+            echo "IMAGE=ghcr.io/kuzminstanislav/catty-reminders-app:$TARGET_SHA" > .env
             
             echo "${{ secrets.GITHUB_TOKEN }}" | sudo docker login ghcr.io -u KuzminStanislav --password-stdin
             
             sudo docker compose pull
+            
+            sudo docker compose --env-file .env down || true
             sudo docker compose --env-file .env up -d --remove-orphans --force-recreate
             
             for i in $(seq 1 30); do
@@ -52,6 +53,6 @@ jobs:
               sleep 3
             done
             
-            echo "App failed to start"
+            echo "App failed"
             sudo docker compose logs app
             exit 1
