update yaml 3

diff --git a/.github/workflows/deploy.yaml b/.github/workflows/deploy.yaml
--- a/.github/workflows/deploy.yaml
+++ b/.github/workflows/deploy.yaml
@@ -9,19 +9,6 @@ jobs:
     runs-on: ubuntu-latest
 
     steps:
-      - name: Checkout repository
-        uses: actions/checkout@v4
-
-      - name: Copy deploy script to server via SSH
-        uses: appleboy/scp-action@v0.1.7
-        with:
-          host: ${{ vars.DEPLOY_HOST }}
-          username: ${{ vars.DEPLOY_USER }}
-          port: ${{ vars.DEPLOY_PORT }}
-          key: ${{ secrets.SSH_PRIVATE_KEY }}
-          source: "deploy.sh"
-          target: "./"
-
       - name: Execute Deploy via SSH
         uses: appleboy/ssh-action@v1.0.3
         with:
@@ -31,9 +18,37 @@ jobs:
           key: ${{ secrets.SSH_PRIVATE_KEY }}
           script: |
             set -e
+            
             OWNER=$(echo "${{ github.repository_owner }}" | tr '[:upper:]' '[:lower:]')
             REPO_NAME=$(echo "${{ github.event.repository.name }}" | tr '[:upper:]' '[:lower:]')
             IMAGE_PATH="ghcr.io/$OWNER/$REPO_NAME"
             
-            chmod +x ./deploy.sh
-            ./deploy.sh $IMAGE_PATH ${{ github.sha }}
+            CONTAINER_NAME="catty-app"
+            HOST_PORT=8181
+            CONTAINER_PORT=8181
+            IMAGE="$IMAGE_PATH:${{ github.sha }}"
+            
+            echo "=== ПОДКЛЮЧЕНИЕ УСПЕШНО ==="
+            echo "Pulling image: $IMAGE"
+            docker pull $IMAGE
+            
+            echo "=== Stopping old container ==="
+            docker stop $CONTAINER_NAME || true
+            docker rm $CONTAINER_NAME || true
+            
+            echo "=== Starting new container ==="
+            docker run -d \
+                -p $HOST_PORT:$CONTAINER_PORT \
+                --name $CONTAINER_NAME \
+                --restart unless-stopped \
+                -e DEPLOY_REF=${{ github.sha }} \
+                $IMAGE
+            
+            sleep 4
+            if docker ps | grep -q $CONTAINER_NAME; then
+                echo "Deployment completed successfully!"
+            else
+                echo "ERROR: Application failed to start"
+                docker logs $CONTAINER_NAME
+                exit 1
+            fi
